import React from 'react'
import PropTypes from 'prop-types';
import request from '../../utils/request-provider';
import APIS from '../../constants/api-constants';

export default class UserTab extends React.Component {
  constructor() {
    super()
    this.state = {
      buttonToggle: true,
      userDetails: []
    }
  }

  showDetails() {
    if (!this.state.buttonToggle) {
      let url = APIS.USER_DETAILS;
      url = url.replace(/{username}/i, this.props.username);
      request.fetch(url).then(response => {
        console.log(response);
        this.setState({
          userDetails: response
        })
      });
    }
  }

  toggleDetails() {
    this.setState({
      buttonToggle: !this.state.buttonToggle
    }, this.showDetails)
  }

  renderUserDetails() {
    if (!this.state.userDetails.length) {
      return (
        <li className="list-group-item details-text-alignment">
          <div className="row">
            <div className="col-md-6">No repositories present</div>
          </div>
        </li>
      )
    }
    let details = _.map(this.state.userDetails, (userDetail) => {
      return (
        <li className="list-group-item details-text-alignment">
          <div className="row">
            <div className="col-md-6">{userDetail.name}</div>
            <div className="col-md-6">{userDetail.language}</div>
          </div>
        </li>
      )
    })
    return details;
  }

  render() {
    return (
      <div>
        <li className="media media-card my-4" key={this.props.id}>
          <img className="mr-3 img-thumbnail img-thumbnail-width-height rounded-circle" src={this.props.profilePic} alt="Generic placeholder image" />
          <div className="media-body">
            <h5 className="mt-0 mb-1">{this.props.username}</h5>
            <p className="profile-url">{`Profile URL: ${this.props.html_url}`}</p>
            <div className="data-details">
              <div className="row">
                <div className="col-md-8">
                  <ul className="list-unstyled">
                    <li>{`score: ${this.props.score}`}</li>
                    <li>Data One</li>
                  </ul>
                </div>
                <div className="col-md-3">
                  <button onClick={this.toggleDetails.bind(this)} type="button" className="btn btn-outline-primary set-details-button" data-toggle="collapse" data-target={`#multiCollapseExample${this.props.id}`} aria-expanded="false" aria-controls={`multiCollapseExample${this.props.id}`}>{this.state.buttonToggle ? 'Details' : 'Collapse'}</button>
                </div>
              </div>
            </div>
          </div>
        </li>
        <div className="collapse multi-collapse" style={{ marginTop: '-1.5rem' }} id={`multiCollapseExample${this.props.id}`}>
          <ul className="list-group">
            {this.renderUserDetails()}
          </ul>
        </div>
      </div>
    )
  }
}
UserTab.propTypes = {
  username: PropTypes.string,
  profilePic: PropTypes.string,
  id: PropTypes.number,
  showDetails: PropTypes.func
};




// [
//   {
//     "id": 75275570,
//     "node_id": "MDEwOlJlcG9zaXRvcnk3NTI3NTU3MA==",
//     "name": "hello-world",
//     "full_name": "riyapahuja1994/hello-world",
//     "owner": {
//       "login": "riyapahuja1994",
//       "id": 22217750,
//       "node_id": "MDQ6VXNlcjIyMjE3NzUw",
//       "avatar_url": "https://avatars0.githubusercontent.com/u/22217750?v=4",
//       "gravatar_id": "",
//       "url": "https://api.github.com/users/riyapahuja1994",
//       "html_url": "https://github.com/riyapahuja1994",
//       "followers_url": "https://api.github.com/users/riyapahuja1994/followers",
//       "following_url": "https://api.github.com/users/riyapahuja1994/following{/other_user}",
//       "gists_url": "https://api.github.com/users/riyapahuja1994/gists{/gist_id}",
//       "starred_url": "https://api.github.com/users/riyapahuja1994/starred{/owner}{/repo}",
//       "subscriptions_url": "https://api.github.com/users/riyapahuja1994/subscriptions",
//       "organizations_url": "https://api.github.com/users/riyapahuja1994/orgs",
//       "repos_url": "https://api.github.com/users/riyapahuja1994/repos",
//       "events_url": "https://api.github.com/users/riyapahuja1994/events{/privacy}",
//       "received_events_url": "https://api.github.com/users/riyapahuja1994/received_events",
//       "type": "User",
//       "site_admin": false
//     },
//     "private": false,
//     "html_url": "https://github.com/riyapahuja1994/hello-world",
//     "description": "Learn Github",
//     "fork": false,
//     "url": "https://api.github.com/repos/riyapahuja1994/hello-world",
//     "forks_url": "https://api.github.com/repos/riyapahuja1994/hello-world/forks",
//     "keys_url": "https://api.github.com/repos/riyapahuja1994/hello-world/keys{/key_id}",
//     "collaborators_url": "https://api.github.com/repos/riyapahuja1994/hello-world/collaborators{/collaborator}",
//     "teams_url": "https://api.github.com/repos/riyapahuja1994/hello-world/teams",
//     "hooks_url": "https://api.github.com/repos/riyapahuja1994/hello-world/hooks",
//     "issue_events_url": "https://api.github.com/repos/riyapahuja1994/hello-world/issues/events{/number}",
//     "events_url": "https://api.github.com/repos/riyapahuja1994/hello-world/events",
//     "assignees_url": "https://api.github.com/repos/riyapahuja1994/hello-world/assignees{/user}",
//     "branches_url": "https://api.github.com/repos/riyapahuja1994/hello-world/branches{/branch}",
//     "tags_url": "https://api.github.com/repos/riyapahuja1994/hello-world/tags",
//     "blobs_url": "https://api.github.com/repos/riyapahuja1994/hello-world/git/blobs{/sha}",
//     "git_tags_url": "https://api.github.com/repos/riyapahuja1994/hello-world/git/tags{/sha}",
//     "git_refs_url": "https://api.github.com/repos/riyapahuja1994/hello-world/git/refs{/sha}",
//     "trees_url": "https://api.github.com/repos/riyapahuja1994/hello-world/git/trees{/sha}",
//     "statuses_url": "https://api.github.com/repos/riyapahuja1994/hello-world/statuses/{sha}",
//     "languages_url": "https://api.github.com/repos/riyapahuja1994/hello-world/languages",
//     "stargazers_url": "https://api.github.com/repos/riyapahuja1994/hello-world/stargazers",
//     "contributors_url": "https://api.github.com/repos/riyapahuja1994/hello-world/contributors",
//     "subscribers_url": "https://api.github.com/repos/riyapahuja1994/hello-world/subscribers",
//     "subscription_url": "https://api.github.com/repos/riyapahuja1994/hello-world/subscription",
//     "commits_url": "https://api.github.com/repos/riyapahuja1994/hello-world/commits{/sha}",
//     "git_commits_url": "https://api.github.com/repos/riyapahuja1994/hello-world/git/commits{/sha}",
//     "comments_url": "https://api.github.com/repos/riyapahuja1994/hello-world/comments{/number}",
//     "issue_comment_url": "https://api.github.com/repos/riyapahuja1994/hello-world/issues/comments{/number}",
//     "contents_url": "https://api.github.com/repos/riyapahuja1994/hello-world/contents/{+path}",
//     "compare_url": "https://api.github.com/repos/riyapahuja1994/hello-world/compare/{base}...{head}",
//     "merges_url": "https://api.github.com/repos/riyapahuja1994/hello-world/merges",
//     "archive_url": "https://api.github.com/repos/riyapahuja1994/hello-world/{archive_format}{/ref}",
//     "downloads_url": "https://api.github.com/repos/riyapahuja1994/hello-world/downloads",
//     "issues_url": "https://api.github.com/repos/riyapahuja1994/hello-world/issues{/number}",
//     "pulls_url": "https://api.github.com/repos/riyapahuja1994/hello-world/pulls{/number}",
//     "milestones_url": "https://api.github.com/repos/riyapahuja1994/hello-world/milestones{/number}",
//     "notifications_url": "https://api.github.com/repos/riyapahuja1994/hello-world/notifications{?since,all,participating}",
//     "labels_url": "https://api.github.com/repos/riyapahuja1994/hello-world/labels{/name}",
//     "releases_url": "https://api.github.com/repos/riyapahuja1994/hello-world/releases{/id}",
//     "deployments_url": "https://api.github.com/repos/riyapahuja1994/hello-world/deployments",
//     "created_at": "2016-12-01T09:16:27Z",
//     "updated_at": "2016-12-01T09:16:27Z",
//     "pushed_at": "2016-12-01T09:38:22Z",
//     "git_url": "git://github.com/riyapahuja1994/hello-world.git",
//     "ssh_url": "git@github.com:riyapahuja1994/hello-world.git",
//     "clone_url": "https://github.com/riyapahuja1994/hello-world.git",
//     "svn_url": "https://github.com/riyapahuja1994/hello-world",
//     "homepage": null,
//     "size": 0,
//     "stargazers_count": 0,
//     "watchers_count": 0,
//     "language": null,
//     "has_issues": true,
//     "has_projects": true,
//     "has_downloads": true,
//     "has_wiki": true,
//     "has_pages": false,
//     "forks_count": 0,
//     "mirror_url": null,
//     "archived": false,
//     "open_issues_count": 0,
//     "license": null,
//     "forks": 0,
//     "open_issues": 0,
//     "watchers": 0,
//     "default_branch": "master"
//   },
//   {
//     "id": 137180267,
//     "node_id": "MDEwOlJlcG9zaXRvcnkxMzcxODAyNjc=",
//     "name": "nodejs-demo-backend",
//     "full_name": "riyapahuja1994/nodejs-demo-backend",
//     "owner": {
//       "login": "riyapahuja1994",
//       "id": 22217750,
//       "node_id": "MDQ6VXNlcjIyMjE3NzUw",
//       "avatar_url": "https://avatars0.githubusercontent.com/u/22217750?v=4",
//       "gravatar_id": "",
//       "url": "https://api.github.com/users/riyapahuja1994",
//       "html_url": "https://github.com/riyapahuja1994",
//       "followers_url": "https://api.github.com/users/riyapahuja1994/followers",
//       "following_url": "https://api.github.com/users/riyapahuja1994/following{/other_user}",
//       "gists_url": "https://api.github.com/users/riyapahuja1994/gists{/gist_id}",
//       "starred_url": "https://api.github.com/users/riyapahuja1994/starred{/owner}{/repo}",
//       "subscriptions_url": "https://api.github.com/users/riyapahuja1994/subscriptions",
//       "organizations_url": "https://api.github.com/users/riyapahuja1994/orgs",
//       "repos_url": "https://api.github.com/users/riyapahuja1994/repos",
//       "events_url": "https://api.github.com/users/riyapahuja1994/events{/privacy}",
//       "received_events_url": "https://api.github.com/users/riyapahuja1994/received_events",
//       "type": "User",
//       "site_admin": false
//     },
//     "private": false,
//     "html_url": "https://github.com/riyapahuja1994/nodejs-demo-backend",
//     "description": null,
//     "fork": false,
//     "url": "https://api.github.com/repos/riyapahuja1994/nodejs-demo-backend",
//     "forks_url": "https://api.github.com/repos/riyapahuja1994/nodejs-demo-backend/forks",
//     "keys_url": "https://api.github.com/repos/riyapahuja1994/nodejs-demo-backend/keys{/key_id}",
//     "collaborators_url": "https://api.github.com/repos/riyapahuja1994/nodejs-demo-backend/collaborators{/collaborator}",
//     "teams_url": "https://api.github.com/repos/riyapahuja1994/nodejs-demo-backend/teams",
//     "hooks_url": "https://api.github.com/repos/riyapahuja1994/nodejs-demo-backend/hooks",
//     "issue_events_url": "https://api.github.com/repos/riyapahuja1994/nodejs-demo-backend/issues/events{/number}",
//     "events_url": "https://api.github.com/repos/riyapahuja1994/nodejs-demo-backend/events",
//     "assignees_url": "https://api.github.com/repos/riyapahuja1994/nodejs-demo-backend/assignees{/user}",
//     "branches_url": "https://api.github.com/repos/riyapahuja1994/nodejs-demo-backend/branches{/branch}",
//     "tags_url": "https://api.github.com/repos/riyapahuja1994/nodejs-demo-backend/tags",
//     "blobs_url": "https://api.github.com/repos/riyapahuja1994/nodejs-demo-backend/git/blobs{/sha}",
//     "git_tags_url": "https://api.github.com/repos/riyapahuja1994/nodejs-demo-backend/git/tags{/sha}",
//     "git_refs_url": "https://api.github.com/repos/riyapahuja1994/nodejs-demo-backend/git/refs{/sha}",
//     "trees_url": "https://api.github.com/repos/riyapahuja1994/nodejs-demo-backend/git/trees{/sha}",
//     "statuses_url": "https://api.github.com/repos/riyapahuja1994/nodejs-demo-backend/statuses/{sha}",
//     "languages_url": "https://api.github.com/repos/riyapahuja1994/nodejs-demo-backend/languages",
//     "stargazers_url": "https://api.github.com/repos/riyapahuja1994/nodejs-demo-backend/stargazers",
//     "contributors_url": "https://api.github.com/repos/riyapahuja1994/nodejs-demo-backend/contributors",
//     "subscribers_url": "https://api.github.com/repos/riyapahuja1994/nodejs-demo-backend/subscribers",
//     "subscription_url": "https://api.github.com/repos/riyapahuja1994/nodejs-demo-backend/subscription",
//     "commits_url": "https://api.github.com/repos/riyapahuja1994/nodejs-demo-backend/commits{/sha}",
//     "git_commits_url": "https://api.github.com/repos/riyapahuja1994/nodejs-demo-backend/git/commits{/sha}",
//     "comments_url": "https://api.github.com/repos/riyapahuja1994/nodejs-demo-backend/comments{/number}",
//     "issue_comment_url": "https://api.github.com/repos/riyapahuja1994/nodejs-demo-backend/issues/comments{/number}",
//     "contents_url": "https://api.github.com/repos/riyapahuja1994/nodejs-demo-backend/contents/{+path}",
//     "compare_url": "https://api.github.com/repos/riyapahuja1994/nodejs-demo-backend/compare/{base}...{head}",
//     "merges_url": "https://api.github.com/repos/riyapahuja1994/nodejs-demo-backend/merges",
//     "archive_url": "https://api.github.com/repos/riyapahuja1994/nodejs-demo-backend/{archive_format}{/ref}",
//     "downloads_url": "https://api.github.com/repos/riyapahuja1994/nodejs-demo-backend/downloads",
//     "issues_url": "https://api.github.com/repos/riyapahuja1994/nodejs-demo-backend/issues{/number}",
//     "pulls_url": "https://api.github.com/repos/riyapahuja1994/nodejs-demo-backend/pulls{/number}",
//     "milestones_url": "https://api.github.com/repos/riyapahuja1994/nodejs-demo-backend/milestones{/number}",
//     "notifications_url": "https://api.github.com/repos/riyapahuja1994/nodejs-demo-backend/notifications{?since,all,participating}",
//     "labels_url": "https://api.github.com/repos/riyapahuja1994/nodejs-demo-backend/labels{/name}",
//     "releases_url": "https://api.github.com/repos/riyapahuja1994/nodejs-demo-backend/releases{/id}",
//     "deployments_url": "https://api.github.com/repos/riyapahuja1994/nodejs-demo-backend/deployments",
//     "created_at": "2018-06-13T07:39:41Z",
//     "updated_at": "2018-06-13T09:44:14Z",
//     "pushed_at": "2018-06-13T09:44:13Z",
//     "git_url": "git://github.com/riyapahuja1994/nodejs-demo-backend.git",
//     "ssh_url": "git@github.com:riyapahuja1994/nodejs-demo-backend.git",
//     "clone_url": "https://github.com/riyapahuja1994/nodejs-demo-backend.git",
//     "svn_url": "https://github.com/riyapahuja1994/nodejs-demo-backend",
//     "homepage": null,
//     "size": 21,
//     "stargazers_count": 0,
//     "watchers_count": 0,
//     "language": "JavaScript",
//     "has_issues": true,
//     "has_projects": true,
//     "has_downloads": true,
//     "has_wiki": true,
//     "has_pages": false,
//     "forks_count": 0,
//     "mirror_url": null,
//     "archived": false,
//     "open_issues_count": 0,
//     "license": null,
//     "forks": 0,
//     "open_issues": 0,
//     "watchers": 0,
//     "default_branch": "master"
//   },
//   {
//     "id": 137178430,
//     "node_id": "MDEwOlJlcG9zaXRvcnkxMzcxNzg0MzA=",
//     "name": "nodejs-demo-frontend",
//     "full_name": "riyapahuja1994/nodejs-demo-frontend",
//     "owner": {
//       "login": "riyapahuja1994",
//       "id": 22217750,
//       "node_id": "MDQ6VXNlcjIyMjE3NzUw",
//       "avatar_url": "https://avatars0.githubusercontent.com/u/22217750?v=4",
//       "gravatar_id": "",
//       "url": "https://api.github.com/users/riyapahuja1994",
//       "html_url": "https://github.com/riyapahuja1994",
//       "followers_url": "https://api.github.com/users/riyapahuja1994/followers",
//       "following_url": "https://api.github.com/users/riyapahuja1994/following{/other_user}",
//       "gists_url": "https://api.github.com/users/riyapahuja1994/gists{/gist_id}",
//       "starred_url": "https://api.github.com/users/riyapahuja1994/starred{/owner}{/repo}",
//       "subscriptions_url": "https://api.github.com/users/riyapahuja1994/subscriptions",
//       "organizations_url": "https://api.github.com/users/riyapahuja1994/orgs",
//       "repos_url": "https://api.github.com/users/riyapahuja1994/repos",
//       "events_url": "https://api.github.com/users/riyapahuja1994/events{/privacy}",
//       "received_events_url": "https://api.github.com/users/riyapahuja1994/received_events",
//       "type": "User",
//       "site_admin": false
//     },
//     "private": false,
//     "html_url": "https://github.com/riyapahuja1994/nodejs-demo-frontend",
//     "description": null,
//     "fork": false,
//     "url": "https://api.github.com/repos/riyapahuja1994/nodejs-demo-frontend",
//     "forks_url": "https://api.github.com/repos/riyapahuja1994/nodejs-demo-frontend/forks",
//     "keys_url": "https://api.github.com/repos/riyapahuja1994/nodejs-demo-frontend/keys{/key_id}",
//     "collaborators_url": "https://api.github.com/repos/riyapahuja1994/nodejs-demo-frontend/collaborators{/collaborator}",
//     "teams_url": "https://api.github.com/repos/riyapahuja1994/nodejs-demo-frontend/teams",
//     "hooks_url": "https://api.github.com/repos/riyapahuja1994/nodejs-demo-frontend/hooks",
//     "issue_events_url": "https://api.github.com/repos/riyapahuja1994/nodejs-demo-frontend/issues/events{/number}",
//     "events_url": "https://api.github.com/repos/riyapahuja1994/nodejs-demo-frontend/events",
//     "assignees_url": "https://api.github.com/repos/riyapahuja1994/nodejs-demo-frontend/assignees{/user}",
//     "branches_url": "https://api.github.com/repos/riyapahuja1994/nodejs-demo-frontend/branches{/branch}",
//     "tags_url": "https://api.github.com/repos/riyapahuja1994/nodejs-demo-frontend/tags",
//     "blobs_url": "https://api.github.com/repos/riyapahuja1994/nodejs-demo-frontend/git/blobs{/sha}",
//     "git_tags_url": "https://api.github.com/repos/riyapahuja1994/nodejs-demo-frontend/git/tags{/sha}",
//     "git_refs_url": "https://api.github.com/repos/riyapahuja1994/nodejs-demo-frontend/git/refs{/sha}",
//     "trees_url": "https://api.github.com/repos/riyapahuja1994/nodejs-demo-frontend/git/trees{/sha}",
//     "statuses_url": "https://api.github.com/repos/riyapahuja1994/nodejs-demo-frontend/statuses/{sha}",
//     "languages_url": "https://api.github.com/repos/riyapahuja1994/nodejs-demo-frontend/languages",
//     "stargazers_url": "https://api.github.com/repos/riyapahuja1994/nodejs-demo-frontend/stargazers",
//     "contributors_url": "https://api.github.com/repos/riyapahuja1994/nodejs-demo-frontend/contributors",
//     "subscribers_url": "https://api.github.com/repos/riyapahuja1994/nodejs-demo-frontend/subscribers",
//     "subscription_url": "https://api.github.com/repos/riyapahuja1994/nodejs-demo-frontend/subscription",
//     "commits_url": "https://api.github.com/repos/riyapahuja1994/nodejs-demo-frontend/commits{/sha}",
//     "git_commits_url": "https://api.github.com/repos/riyapahuja1994/nodejs-demo-frontend/git/commits{/sha}",
//     "comments_url": "https://api.github.com/repos/riyapahuja1994/nodejs-demo-frontend/comments{/number}",
//     "issue_comment_url": "https://api.github.com/repos/riyapahuja1994/nodejs-demo-frontend/issues/comments{/number}",
//     "contents_url": "https://api.github.com/repos/riyapahuja1994/nodejs-demo-frontend/contents/{+path}",
//     "compare_url": "https://api.github.com/repos/riyapahuja1994/nodejs-demo-frontend/compare/{base}...{head}",
//     "merges_url": "https://api.github.com/repos/riyapahuja1994/nodejs-demo-frontend/merges",
//     "archive_url": "https://api.github.com/repos/riyapahuja1994/nodejs-demo-frontend/{archive_format}{/ref}",
//     "downloads_url": "https://api.github.com/repos/riyapahuja1994/nodejs-demo-frontend/downloads",
//     "issues_url": "https://api.github.com/repos/riyapahuja1994/nodejs-demo-frontend/issues{/number}",
//     "pulls_url": "https://api.github.com/repos/riyapahuja1994/nodejs-demo-frontend/pulls{/number}",
//     "milestones_url": "https://api.github.com/repos/riyapahuja1994/nodejs-demo-frontend/milestones{/number}",
//     "notifications_url": "https://api.github.com/repos/riyapahuja1994/nodejs-demo-frontend/notifications{?since,all,participating}",
//     "labels_url": "https://api.github.com/repos/riyapahuja1994/nodejs-demo-frontend/labels{/name}",
//     "releases_url": "https://api.github.com/repos/riyapahuja1994/nodejs-demo-frontend/releases{/id}",
//     "deployments_url": "https://api.github.com/repos/riyapahuja1994/nodejs-demo-frontend/deployments",
//     "created_at": "2018-06-13T07:24:05Z",
//     "updated_at": "2018-06-13T07:26:46Z",
//     "pushed_at": "2018-06-13T07:26:43Z",
//     "git_url": "git://github.com/riyapahuja1994/nodejs-demo-frontend.git",
//     "ssh_url": "git@github.com:riyapahuja1994/nodejs-demo-frontend.git",
//     "clone_url": "https://github.com/riyapahuja1994/nodejs-demo-frontend.git",
//     "svn_url": "https://github.com/riyapahuja1994/nodejs-demo-frontend",
//     "homepage": null,
//     "size": 116,
//     "stargazers_count": 0,
//     "watchers_count": 0,
//     "language": "TypeScript",
//     "has_issues": true,
//     "has_projects": true,
//     "has_downloads": true,
//     "has_wiki": true,
//     "has_pages": false,
//     "forks_count": 0,
//     "mirror_url": null,
//     "archived": false,
//     "open_issues_count": 0,
//     "license": null,
//     "forks": 0,
//     "open_issues": 0,
//     "watchers": 0,
//     "default_branch": "master"
//   },
//   {
//     "id": 123459801,
//     "node_id": "MDEwOlJlcG9zaXRvcnkxMjM0NTk4MDE=",
//     "name": "Pipes_Forms_Ang5",
//     "full_name": "riyapahuja1994/Pipes_Forms_Ang5",
//     "owner": {
//       "login": "riyapahuja1994",
//       "id": 22217750,
//       "node_id": "MDQ6VXNlcjIyMjE3NzUw",
//       "avatar_url": "https://avatars0.githubusercontent.com/u/22217750?v=4",
//       "gravatar_id": "",
//       "url": "https://api.github.com/users/riyapahuja1994",
//       "html_url": "https://github.com/riyapahuja1994",
//       "followers_url": "https://api.github.com/users/riyapahuja1994/followers",
//       "following_url": "https://api.github.com/users/riyapahuja1994/following{/other_user}",
//       "gists_url": "https://api.github.com/users/riyapahuja1994/gists{/gist_id}",
//       "starred_url": "https://api.github.com/users/riyapahuja1994/starred{/owner}{/repo}",
//       "subscriptions_url": "https://api.github.com/users/riyapahuja1994/subscriptions",
//       "organizations_url": "https://api.github.com/users/riyapahuja1994/orgs",
//       "repos_url": "https://api.github.com/users/riyapahuja1994/repos",
//       "events_url": "https://api.github.com/users/riyapahuja1994/events{/privacy}",
//       "received_events_url": "https://api.github.com/users/riyapahuja1994/received_events",
//       "type": "User",
//       "site_admin": false
//     },
//     "private": false,
//     "html_url": "https://github.com/riyapahuja1994/Pipes_Forms_Ang5",
//     "description": null,
//     "fork": false,
//     "url": "https://api.github.com/repos/riyapahuja1994/Pipes_Forms_Ang5",
//     "forks_url": "https://api.github.com/repos/riyapahuja1994/Pipes_Forms_Ang5/forks",
//     "keys_url": "https://api.github.com/repos/riyapahuja1994/Pipes_Forms_Ang5/keys{/key_id}",
//     "collaborators_url": "https://api.github.com/repos/riyapahuja1994/Pipes_Forms_Ang5/collaborators{/collaborator}",
//     "teams_url": "https://api.github.com/repos/riyapahuja1994/Pipes_Forms_Ang5/teams",
//     "hooks_url": "https://api.github.com/repos/riyapahuja1994/Pipes_Forms_Ang5/hooks",
//     "issue_events_url": "https://api.github.com/repos/riyapahuja1994/Pipes_Forms_Ang5/issues/events{/number}",
//     "events_url": "https://api.github.com/repos/riyapahuja1994/Pipes_Forms_Ang5/events",
//     "assignees_url": "https://api.github.com/repos/riyapahuja1994/Pipes_Forms_Ang5/assignees{/user}",
//     "branches_url": "https://api.github.com/repos/riyapahuja1994/Pipes_Forms_Ang5/branches{/branch}",
//     "tags_url": "https://api.github.com/repos/riyapahuja1994/Pipes_Forms_Ang5/tags",
//     "blobs_url": "https://api.github.com/repos/riyapahuja1994/Pipes_Forms_Ang5/git/blobs{/sha}",
//     "git_tags_url": "https://api.github.com/repos/riyapahuja1994/Pipes_Forms_Ang5/git/tags{/sha}",
//     "git_refs_url": "https://api.github.com/repos/riyapahuja1994/Pipes_Forms_Ang5/git/refs{/sha}",
//     "trees_url": "https://api.github.com/repos/riyapahuja1994/Pipes_Forms_Ang5/git/trees{/sha}",
//     "statuses_url": "https://api.github.com/repos/riyapahuja1994/Pipes_Forms_Ang5/statuses/{sha}",
//     "languages_url": "https://api.github.com/repos/riyapahuja1994/Pipes_Forms_Ang5/languages",
//     "stargazers_url": "https://api.github.com/repos/riyapahuja1994/Pipes_Forms_Ang5/stargazers",
//     "contributors_url": "https://api.github.com/repos/riyapahuja1994/Pipes_Forms_Ang5/contributors",
//     "subscribers_url": "https://api.github.com/repos/riyapahuja1994/Pipes_Forms_Ang5/subscribers",
//     "subscription_url": "https://api.github.com/repos/riyapahuja1994/Pipes_Forms_Ang5/subscription",
//     "commits_url": "https://api.github.com/repos/riyapahuja1994/Pipes_Forms_Ang5/commits{/sha}",
//     "git_commits_url": "https://api.github.com/repos/riyapahuja1994/Pipes_Forms_Ang5/git/commits{/sha}",
//     "comments_url": "https://api.github.com/repos/riyapahuja1994/Pipes_Forms_Ang5/comments{/number}",
//     "issue_comment_url": "https://api.github.com/repos/riyapahuja1994/Pipes_Forms_Ang5/issues/comments{/number}",
//     "contents_url": "https://api.github.com/repos/riyapahuja1994/Pipes_Forms_Ang5/contents/{+path}",
//     "compare_url": "https://api.github.com/repos/riyapahuja1994/Pipes_Forms_Ang5/compare/{base}...{head}",
//     "merges_url": "https://api.github.com/repos/riyapahuja1994/Pipes_Forms_Ang5/merges",
//     "archive_url": "https://api.github.com/repos/riyapahuja1994/Pipes_Forms_Ang5/{archive_format}{/ref}",
//     "downloads_url": "https://api.github.com/repos/riyapahuja1994/Pipes_Forms_Ang5/downloads",
//     "issues_url": "https://api.github.com/repos/riyapahuja1994/Pipes_Forms_Ang5/issues{/number}",
//     "pulls_url": "https://api.github.com/repos/riyapahuja1994/Pipes_Forms_Ang5/pulls{/number}",
//     "milestones_url": "https://api.github.com/repos/riyapahuja1994/Pipes_Forms_Ang5/milestones{/number}",
//     "notifications_url": "https://api.github.com/repos/riyapahuja1994/Pipes_Forms_Ang5/notifications{?since,all,participating}",
//     "labels_url": "https://api.github.com/repos/riyapahuja1994/Pipes_Forms_Ang5/labels{/name}",
//     "releases_url": "https://api.github.com/repos/riyapahuja1994/Pipes_Forms_Ang5/releases{/id}",
//     "deployments_url": "https://api.github.com/repos/riyapahuja1994/Pipes_Forms_Ang5/deployments",
//     "created_at": "2018-03-01T16:16:21Z",
//     "updated_at": "2018-03-01T16:19:34Z",
//     "pushed_at": "2018-03-01T16:19:33Z",
//     "git_url": "git://github.com/riyapahuja1994/Pipes_Forms_Ang5.git",
//     "ssh_url": "git@github.com:riyapahuja1994/Pipes_Forms_Ang5.git",
//     "clone_url": "https://github.com/riyapahuja1994/Pipes_Forms_Ang5.git",
//     "svn_url": "https://github.com/riyapahuja1994/Pipes_Forms_Ang5",
//     "homepage": null,
//     "size": 100,
//     "stargazers_count": 0,
//     "watchers_count": 0,
//     "language": "TypeScript",
//     "has_issues": true,
//     "has_projects": true,
//     "has_downloads": true,
//     "has_wiki": true,
//     "has_pages": false,
//     "forks_count": 0,
//     "mirror_url": null,
//     "archived": false,
//     "open_issues_count": 0,
//     "license": null,
//     "forks": 0,
//     "open_issues": 0,
//     "watchers": 0,
//     "default_branch": "master"
//   },
//   {
//     "id": 123455256,
//     "node_id": "MDEwOlJlcG9zaXRvcnkxMjM0NTUyNTY=",
//     "name": "recipe_angular5",
//     "full_name": "riyapahuja1994/recipe_angular5",
//     "owner": {
//       "login": "riyapahuja1994",
//       "id": 22217750,
//       "node_id": "MDQ6VXNlcjIyMjE3NzUw",
//       "avatar_url": "https://avatars0.githubusercontent.com/u/22217750?v=4",
//       "gravatar_id": "",
//       "url": "https://api.github.com/users/riyapahuja1994",
//       "html_url": "https://github.com/riyapahuja1994",
//       "followers_url": "https://api.github.com/users/riyapahuja1994/followers",
//       "following_url": "https://api.github.com/users/riyapahuja1994/following{/other_user}",
//       "gists_url": "https://api.github.com/users/riyapahuja1994/gists{/gist_id}",
//       "starred_url": "https://api.github.com/users/riyapahuja1994/starred{/owner}{/repo}",
//       "subscriptions_url": "https://api.github.com/users/riyapahuja1994/subscriptions",
//       "organizations_url": "https://api.github.com/users/riyapahuja1994/orgs",
//       "repos_url": "https://api.github.com/users/riyapahuja1994/repos",
//       "events_url": "https://api.github.com/users/riyapahuja1994/events{/privacy}",
//       "received_events_url": "https://api.github.com/users/riyapahuja1994/received_events",
//       "type": "User",
//       "site_admin": false
//     },
//     "private": false,
//     "html_url": "https://github.com/riyapahuja1994/recipe_angular5",
//     "description": "An angular5 based application",
//     "fork": false,
//     "url": "https://api.github.com/repos/riyapahuja1994/recipe_angular5",
//     "forks_url": "https://api.github.com/repos/riyapahuja1994/recipe_angular5/forks",
//     "keys_url": "https://api.github.com/repos/riyapahuja1994/recipe_angular5/keys{/key_id}",
//     "collaborators_url": "https://api.github.com/repos/riyapahuja1994/recipe_angular5/collaborators{/collaborator}",
//     "teams_url": "https://api.github.com/repos/riyapahuja1994/recipe_angular5/teams",
//     "hooks_url": "https://api.github.com/repos/riyapahuja1994/recipe_angular5/hooks",
//     "issue_events_url": "https://api.github.com/repos/riyapahuja1994/recipe_angular5/issues/events{/number}",
//     "events_url": "https://api.github.com/repos/riyapahuja1994/recipe_angular5/events",
//     "assignees_url": "https://api.github.com/repos/riyapahuja1994/recipe_angular5/assignees{/user}",
//     "branches_url": "https://api.github.com/repos/riyapahuja1994/recipe_angular5/branches{/branch}",
//     "tags_url": "https://api.github.com/repos/riyapahuja1994/recipe_angular5/tags",
//     "blobs_url": "https://api.github.com/repos/riyapahuja1994/recipe_angular5/git/blobs{/sha}",
//     "git_tags_url": "https://api.github.com/repos/riyapahuja1994/recipe_angular5/git/tags{/sha}",
//     "git_refs_url": "https://api.github.com/repos/riyapahuja1994/recipe_angular5/git/refs{/sha}",
//     "trees_url": "https://api.github.com/repos/riyapahuja1994/recipe_angular5/git/trees{/sha}",
//     "statuses_url": "https://api.github.com/repos/riyapahuja1994/recipe_angular5/statuses/{sha}",
//     "languages_url": "https://api.github.com/repos/riyapahuja1994/recipe_angular5/languages",
//     "stargazers_url": "https://api.github.com/repos/riyapahuja1994/recipe_angular5/stargazers",
//     "contributors_url": "https://api.github.com/repos/riyapahuja1994/recipe_angular5/contributors",
//     "subscribers_url": "https://api.github.com/repos/riyapahuja1994/recipe_angular5/subscribers",
//     "subscription_url": "https://api.github.com/repos/riyapahuja1994/recipe_angular5/subscription",
//     "commits_url": "https://api.github.com/repos/riyapahuja1994/recipe_angular5/commits{/sha}",
//     "git_commits_url": "https://api.github.com/repos/riyapahuja1994/recipe_angular5/git/commits{/sha}",
//     "comments_url": "https://api.github.com/repos/riyapahuja1994/recipe_angular5/comments{/number}",
//     "issue_comment_url": "https://api.github.com/repos/riyapahuja1994/recipe_angular5/issues/comments{/number}",
//     "contents_url": "https://api.github.com/repos/riyapahuja1994/recipe_angular5/contents/{+path}",
//     "compare_url": "https://api.github.com/repos/riyapahuja1994/recipe_angular5/compare/{base}...{head}",
//     "merges_url": "https://api.github.com/repos/riyapahuja1994/recipe_angular5/merges",
//     "archive_url": "https://api.github.com/repos/riyapahuja1994/recipe_angular5/{archive_format}{/ref}",
//     "downloads_url": "https://api.github.com/repos/riyapahuja1994/recipe_angular5/downloads",
//     "issues_url": "https://api.github.com/repos/riyapahuja1994/recipe_angular5/issues{/number}",
//     "pulls_url": "https://api.github.com/repos/riyapahuja1994/recipe_angular5/pulls{/number}",
//     "milestones_url": "https://api.github.com/repos/riyapahuja1994/recipe_angular5/milestones{/number}",
//     "notifications_url": "https://api.github.com/repos/riyapahuja1994/recipe_angular5/notifications{?since,all,participating}",
//     "labels_url": "https://api.github.com/repos/riyapahuja1994/recipe_angular5/labels{/name}",
//     "releases_url": "https://api.github.com/repos/riyapahuja1994/recipe_angular5/releases{/id}",
//     "deployments_url": "https://api.github.com/repos/riyapahuja1994/recipe_angular5/deployments",
//     "created_at": "2018-03-01T15:39:53Z",
//     "updated_at": "2018-03-01T15:53:02Z",
//     "pushed_at": "2018-03-09T17:28:38Z",
//     "git_url": "git://github.com/riyapahuja1994/recipe_angular5.git",
//     "ssh_url": "git@github.com:riyapahuja1994/recipe_angular5.git",
//     "clone_url": "https://github.com/riyapahuja1994/recipe_angular5.git",
//     "svn_url": "https://github.com/riyapahuja1994/recipe_angular5",
//     "homepage": null,
//     "size": 152,
//     "stargazers_count": 0,
//     "watchers_count": 0,
//     "language": "TypeScript",
//     "has_issues": true,
//     "has_projects": true,
//     "has_downloads": true,
//     "has_wiki": true,
//     "has_pages": false,
//     "forks_count": 0,
//     "mirror_url": null,
//     "archived": false,
//     "open_issues_count": 0,
//     "license": null,
//     "forks": 0,
//     "open_issues": 0,
//     "watchers": 0,
//     "default_branch": "master"
//   },
//   {
//     "id": 123459195,
//     "node_id": "MDEwOlJlcG9zaXRvcnkxMjM0NTkxOTU=",
//     "name": "Routing_Guards_ang5",
//     "full_name": "riyapahuja1994/Routing_Guards_ang5",
//     "owner": {
//       "login": "riyapahuja1994",
//       "id": 22217750,
//       "node_id": "MDQ6VXNlcjIyMjE3NzUw",
//       "avatar_url": "https://avatars0.githubusercontent.com/u/22217750?v=4",
//       "gravatar_id": "",
//       "url": "https://api.github.com/users/riyapahuja1994",
//       "html_url": "https://github.com/riyapahuja1994",
//       "followers_url": "https://api.github.com/users/riyapahuja1994/followers",
//       "following_url": "https://api.github.com/users/riyapahuja1994/following{/other_user}",
//       "gists_url": "https://api.github.com/users/riyapahuja1994/gists{/gist_id}",
//       "starred_url": "https://api.github.com/users/riyapahuja1994/starred{/owner}{/repo}",
//       "subscriptions_url": "https://api.github.com/users/riyapahuja1994/subscriptions",
//       "organizations_url": "https://api.github.com/users/riyapahuja1994/orgs",
//       "repos_url": "https://api.github.com/users/riyapahuja1994/repos",
//       "events_url": "https://api.github.com/users/riyapahuja1994/events{/privacy}",
//       "received_events_url": "https://api.github.com/users/riyapahuja1994/received_events",
//       "type": "User",
//       "site_admin": false
//     },
//     "private": false,
//     "html_url": "https://github.com/riyapahuja1994/Routing_Guards_ang5",
//     "description": null,
//     "fork": false,
//     "url": "https://api.github.com/repos/riyapahuja1994/Routing_Guards_ang5",
//     "forks_url": "https://api.github.com/repos/riyapahuja1994/Routing_Guards_ang5/forks",
//     "keys_url": "https://api.github.com/repos/riyapahuja1994/Routing_Guards_ang5/keys{/key_id}",
//     "collaborators_url": "https://api.github.com/repos/riyapahuja1994/Routing_Guards_ang5/collaborators{/collaborator}",
//     "teams_url": "https://api.github.com/repos/riyapahuja1994/Routing_Guards_ang5/teams",
//     "hooks_url": "https://api.github.com/repos/riyapahuja1994/Routing_Guards_ang5/hooks",
//     "issue_events_url": "https://api.github.com/repos/riyapahuja1994/Routing_Guards_ang5/issues/events{/number}",
//     "events_url": "https://api.github.com/repos/riyapahuja1994/Routing_Guards_ang5/events",
//     "assignees_url": "https://api.github.com/repos/riyapahuja1994/Routing_Guards_ang5/assignees{/user}",
//     "branches_url": "https://api.github.com/repos/riyapahuja1994/Routing_Guards_ang5/branches{/branch}",
//     "tags_url": "https://api.github.com/repos/riyapahuja1994/Routing_Guards_ang5/tags",
//     "blobs_url": "https://api.github.com/repos/riyapahuja1994/Routing_Guards_ang5/git/blobs{/sha}",
//     "git_tags_url": "https://api.github.com/repos/riyapahuja1994/Routing_Guards_ang5/git/tags{/sha}",
//     "git_refs_url": "https://api.github.com/repos/riyapahuja1994/Routing_Guards_ang5/git/refs{/sha}",
//     "trees_url": "https://api.github.com/repos/riyapahuja1994/Routing_Guards_ang5/git/trees{/sha}",
//     "statuses_url": "https://api.github.com/repos/riyapahuja1994/Routing_Guards_ang5/statuses/{sha}",
//     "languages_url": "https://api.github.com/repos/riyapahuja1994/Routing_Guards_ang5/languages",
//     "stargazers_url": "https://api.github.com/repos/riyapahuja1994/Routing_Guards_ang5/stargazers",
//     "contributors_url": "https://api.github.com/repos/riyapahuja1994/Routing_Guards_ang5/contributors",
//     "subscribers_url": "https://api.github.com/repos/riyapahuja1994/Routing_Guards_ang5/subscribers",
//     "subscription_url": "https://api.github.com/repos/riyapahuja1994/Routing_Guards_ang5/subscription",
//     "commits_url": "https://api.github.com/repos/riyapahuja1994/Routing_Guards_ang5/commits{/sha}",
//     "git_commits_url": "https://api.github.com/repos/riyapahuja1994/Routing_Guards_ang5/git/commits{/sha}",
//     "comments_url": "https://api.github.com/repos/riyapahuja1994/Routing_Guards_ang5/comments{/number}",
//     "issue_comment_url": "https://api.github.com/repos/riyapahuja1994/Routing_Guards_ang5/issues/comments{/number}",
//     "contents_url": "https://api.github.com/repos/riyapahuja1994/Routing_Guards_ang5/contents/{+path}",
//     "compare_url": "https://api.github.com/repos/riyapahuja1994/Routing_Guards_ang5/compare/{base}...{head}",
//     "merges_url": "https://api.github.com/repos/riyapahuja1994/Routing_Guards_ang5/merges",
//     "archive_url": "https://api.github.com/repos/riyapahuja1994/Routing_Guards_ang5/{archive_format}{/ref}",
//     "downloads_url": "https://api.github.com/repos/riyapahuja1994/Routing_Guards_ang5/downloads",
//     "issues_url": "https://api.github.com/repos/riyapahuja1994/Routing_Guards_ang5/issues{/number}",
//     "pulls_url": "https://api.github.com/repos/riyapahuja1994/Routing_Guards_ang5/pulls{/number}",
//     "milestones_url": "https://api.github.com/repos/riyapahuja1994/Routing_Guards_ang5/milestones{/number}",
//     "notifications_url": "https://api.github.com/repos/riyapahuja1994/Routing_Guards_ang5/notifications{?since,all,participating}",
//     "labels_url": "https://api.github.com/repos/riyapahuja1994/Routing_Guards_ang5/labels{/name}",
//     "releases_url": "https://api.github.com/repos/riyapahuja1994/Routing_Guards_ang5/releases{/id}",
//     "deployments_url": "https://api.github.com/repos/riyapahuja1994/Routing_Guards_ang5/deployments",
//     "created_at": "2018-03-01T16:11:30Z",
//     "updated_at": "2018-03-01T16:14:40Z",
//     "pushed_at": "2018-03-01T16:14:39Z",
//     "git_url": "git://github.com/riyapahuja1994/Routing_Guards_ang5.git",
//     "ssh_url": "git@github.com:riyapahuja1994/Routing_Guards_ang5.git",
//     "clone_url": "https://github.com/riyapahuja1994/Routing_Guards_ang5.git",
//     "svn_url": "https://github.com/riyapahuja1994/Routing_Guards_ang5",
//     "homepage": null,
//     "size": 108,
//     "stargazers_count": 0,
//     "watchers_count": 0,
//     "language": "TypeScript",
//     "has_issues": true,
//     "has_projects": true,
//     "has_downloads": true,
//     "has_wiki": true,
//     "has_pages": false,
//     "forks_count": 0,
//     "mirror_url": null,
//     "archived": false,
//     "open_issues_count": 0,
//     "license": null,
//     "forks": 0,
//     "open_issues": 0,
//     "watchers": 0,
//     "default_branch": "master"
//   },
//   {
//     "id": 130953682,
//     "node_id": "MDEwOlJlcG9zaXRvcnkxMzA5NTM2ODI=",
//     "name": "svgAnimationModule",
//     "full_name": "riyapahuja1994/svgAnimationModule",
//     "owner": {
//       "login": "riyapahuja1994",
//       "id": 22217750,
//       "node_id": "MDQ6VXNlcjIyMjE3NzUw",
//       "avatar_url": "https://avatars0.githubusercontent.com/u/22217750?v=4",
//       "gravatar_id": "",
//       "url": "https://api.github.com/users/riyapahuja1994",
//       "html_url": "https://github.com/riyapahuja1994",
//       "followers_url": "https://api.github.com/users/riyapahuja1994/followers",
//       "following_url": "https://api.github.com/users/riyapahuja1994/following{/other_user}",
//       "gists_url": "https://api.github.com/users/riyapahuja1994/gists{/gist_id}",
//       "starred_url": "https://api.github.com/users/riyapahuja1994/starred{/owner}{/repo}",
//       "subscriptions_url": "https://api.github.com/users/riyapahuja1994/subscriptions",
//       "organizations_url": "https://api.github.com/users/riyapahuja1994/orgs",
//       "repos_url": "https://api.github.com/users/riyapahuja1994/repos",
//       "events_url": "https://api.github.com/users/riyapahuja1994/events{/privacy}",
//       "received_events_url": "https://api.github.com/users/riyapahuja1994/received_events",
//       "type": "User",
//       "site_admin": false
//     },
//     "private": false,
//     "html_url": "https://github.com/riyapahuja1994/svgAnimationModule",
//     "description": null,
//     "fork": false,
//     "url": "https://api.github.com/repos/riyapahuja1994/svgAnimationModule",
//     "forks_url": "https://api.github.com/repos/riyapahuja1994/svgAnimationModule/forks",
//     "keys_url": "https://api.github.com/repos/riyapahuja1994/svgAnimationModule/keys{/key_id}",
//     "collaborators_url": "https://api.github.com/repos/riyapahuja1994/svgAnimationModule/collaborators{/collaborator}",
//     "teams_url": "https://api.github.com/repos/riyapahuja1994/svgAnimationModule/teams",
//     "hooks_url": "https://api.github.com/repos/riyapahuja1994/svgAnimationModule/hooks",
//     "issue_events_url": "https://api.github.com/repos/riyapahuja1994/svgAnimationModule/issues/events{/number}",
//     "events_url": "https://api.github.com/repos/riyapahuja1994/svgAnimationModule/events",
//     "assignees_url": "https://api.github.com/repos/riyapahuja1994/svgAnimationModule/assignees{/user}",
//     "branches_url": "https://api.github.com/repos/riyapahuja1994/svgAnimationModule/branches{/branch}",
//     "tags_url": "https://api.github.com/repos/riyapahuja1994/svgAnimationModule/tags",
//     "blobs_url": "https://api.github.com/repos/riyapahuja1994/svgAnimationModule/git/blobs{/sha}",
//     "git_tags_url": "https://api.github.com/repos/riyapahuja1994/svgAnimationModule/git/tags{/sha}",
//     "git_refs_url": "https://api.github.com/repos/riyapahuja1994/svgAnimationModule/git/refs{/sha}",
//     "trees_url": "https://api.github.com/repos/riyapahuja1994/svgAnimationModule/git/trees{/sha}",
//     "statuses_url": "https://api.github.com/repos/riyapahuja1994/svgAnimationModule/statuses/{sha}",
//     "languages_url": "https://api.github.com/repos/riyapahuja1994/svgAnimationModule/languages",
//     "stargazers_url": "https://api.github.com/repos/riyapahuja1994/svgAnimationModule/stargazers",
//     "contributors_url": "https://api.github.com/repos/riyapahuja1994/svgAnimationModule/contributors",
//     "subscribers_url": "https://api.github.com/repos/riyapahuja1994/svgAnimationModule/subscribers",
//     "subscription_url": "https://api.github.com/repos/riyapahuja1994/svgAnimationModule/subscription",
//     "commits_url": "https://api.github.com/repos/riyapahuja1994/svgAnimationModule/commits{/sha}",
//     "git_commits_url": "https://api.github.com/repos/riyapahuja1994/svgAnimationModule/git/commits{/sha}",
//     "comments_url": "https://api.github.com/repos/riyapahuja1994/svgAnimationModule/comments{/number}",
//     "issue_comment_url": "https://api.github.com/repos/riyapahuja1994/svgAnimationModule/issues/comments{/number}",
//     "contents_url": "https://api.github.com/repos/riyapahuja1994/svgAnimationModule/contents/{+path}",
//     "compare_url": "https://api.github.com/repos/riyapahuja1994/svgAnimationModule/compare/{base}...{head}",
//     "merges_url": "https://api.github.com/repos/riyapahuja1994/svgAnimationModule/merges",
//     "archive_url": "https://api.github.com/repos/riyapahuja1994/svgAnimationModule/{archive_format}{/ref}",
//     "downloads_url": "https://api.github.com/repos/riyapahuja1994/svgAnimationModule/downloads",
//     "issues_url": "https://api.github.com/repos/riyapahuja1994/svgAnimationModule/issues{/number}",
//     "pulls_url": "https://api.github.com/repos/riyapahuja1994/svgAnimationModule/pulls{/number}",
//     "milestones_url": "https://api.github.com/repos/riyapahuja1994/svgAnimationModule/milestones{/number}",
//     "notifications_url": "https://api.github.com/repos/riyapahuja1994/svgAnimationModule/notifications{?since,all,participating}",
//     "labels_url": "https://api.github.com/repos/riyapahuja1994/svgAnimationModule/labels{/name}",
//     "releases_url": "https://api.github.com/repos/riyapahuja1994/svgAnimationModule/releases{/id}",
//     "deployments_url": "https://api.github.com/repos/riyapahuja1994/svgAnimationModule/deployments",
//     "created_at": "2018-04-25T05:11:00Z",
//     "updated_at": "2018-04-25T05:15:39Z",
//     "pushed_at": "2018-04-25T05:15:38Z",
//     "git_url": "git://github.com/riyapahuja1994/svgAnimationModule.git",
//     "ssh_url": "git@github.com:riyapahuja1994/svgAnimationModule.git",
//     "clone_url": "https://github.com/riyapahuja1994/svgAnimationModule.git",
//     "svn_url": "https://github.com/riyapahuja1994/svgAnimationModule",
//     "homepage": null,
//     "size": 67,
//     "stargazers_count": 0,
//     "watchers_count": 0,
//     "language": "HTML",
//     "has_issues": true,
//     "has_projects": true,
//     "has_downloads": true,
//     "has_wiki": true,
//     "has_pages": false,
//     "forks_count": 0,
//     "mirror_url": null,
//     "archived": false,
//     "open_issues_count": 0,
//     "license": null,
//     "forks": 0,
//     "open_issues": 0,
//     "watchers": 0,
//     "default_branch": "master"
//   },
//   {
//     "id": 111763975,
//     "node_id": "MDEwOlJlcG9zaXRvcnkxMTE3NjM5NzU=",
//     "name": "wakeme",
//     "full_name": "riyapahuja1994/wakeme",
//     "owner": {
//       "login": "riyapahuja1994",
//       "id": 22217750,
//       "node_id": "MDQ6VXNlcjIyMjE3NzUw",
//       "avatar_url": "https://avatars0.githubusercontent.com/u/22217750?v=4",
//       "gravatar_id": "",
//       "url": "https://api.github.com/users/riyapahuja1994",
//       "html_url": "https://github.com/riyapahuja1994",
//       "followers_url": "https://api.github.com/users/riyapahuja1994/followers",
//       "following_url": "https://api.github.com/users/riyapahuja1994/following{/other_user}",
//       "gists_url": "https://api.github.com/users/riyapahuja1994/gists{/gist_id}",
//       "starred_url": "https://api.github.com/users/riyapahuja1994/starred{/owner}{/repo}",
//       "subscriptions_url": "https://api.github.com/users/riyapahuja1994/subscriptions",
//       "organizations_url": "https://api.github.com/users/riyapahuja1994/orgs",
//       "repos_url": "https://api.github.com/users/riyapahuja1994/repos",
//       "events_url": "https://api.github.com/users/riyapahuja1994/events{/privacy}",
//       "received_events_url": "https://api.github.com/users/riyapahuja1994/received_events",
//       "type": "User",
//       "site_admin": false
//     },
//     "private": false,
//     "html_url": "https://github.com/riyapahuja1994/wakeme",
//     "description": "Ionic 2 based application using google maps apis",
//     "fork": false,
//     "url": "https://api.github.com/repos/riyapahuja1994/wakeme",
//     "forks_url": "https://api.github.com/repos/riyapahuja1994/wakeme/forks",
//     "keys_url": "https://api.github.com/repos/riyapahuja1994/wakeme/keys{/key_id}",
//     "collaborators_url": "https://api.github.com/repos/riyapahuja1994/wakeme/collaborators{/collaborator}",
//     "teams_url": "https://api.github.com/repos/riyapahuja1994/wakeme/teams",
//     "hooks_url": "https://api.github.com/repos/riyapahuja1994/wakeme/hooks",
//     "issue_events_url": "https://api.github.com/repos/riyapahuja1994/wakeme/issues/events{/number}",
//     "events_url": "https://api.github.com/repos/riyapahuja1994/wakeme/events",
//     "assignees_url": "https://api.github.com/repos/riyapahuja1994/wakeme/assignees{/user}",
//     "branches_url": "https://api.github.com/repos/riyapahuja1994/wakeme/branches{/branch}",
//     "tags_url": "https://api.github.com/repos/riyapahuja1994/wakeme/tags",
//     "blobs_url": "https://api.github.com/repos/riyapahuja1994/wakeme/git/blobs{/sha}",
//     "git_tags_url": "https://api.github.com/repos/riyapahuja1994/wakeme/git/tags{/sha}",
//     "git_refs_url": "https://api.github.com/repos/riyapahuja1994/wakeme/git/refs{/sha}",
//     "trees_url": "https://api.github.com/repos/riyapahuja1994/wakeme/git/trees{/sha}",
//     "statuses_url": "https://api.github.com/repos/riyapahuja1994/wakeme/statuses/{sha}",
//     "languages_url": "https://api.github.com/repos/riyapahuja1994/wakeme/languages",
//     "stargazers_url": "https://api.github.com/repos/riyapahuja1994/wakeme/stargazers",
//     "contributors_url": "https://api.github.com/repos/riyapahuja1994/wakeme/contributors",
//     "subscribers_url": "https://api.github.com/repos/riyapahuja1994/wakeme/subscribers",
//     "subscription_url": "https://api.github.com/repos/riyapahuja1994/wakeme/subscription",
//     "commits_url": "https://api.github.com/repos/riyapahuja1994/wakeme/commits{/sha}",
//     "git_commits_url": "https://api.github.com/repos/riyapahuja1994/wakeme/git/commits{/sha}",
//     "comments_url": "https://api.github.com/repos/riyapahuja1994/wakeme/comments{/number}",
//     "issue_comment_url": "https://api.github.com/repos/riyapahuja1994/wakeme/issues/comments{/number}",
//     "contents_url": "https://api.github.com/repos/riyapahuja1994/wakeme/contents/{+path}",
//     "compare_url": "https://api.github.com/repos/riyapahuja1994/wakeme/compare/{base}...{head}",
//     "merges_url": "https://api.github.com/repos/riyapahuja1994/wakeme/merges",
//     "archive_url": "https://api.github.com/repos/riyapahuja1994/wakeme/{archive_format}{/ref}",
//     "downloads_url": "https://api.github.com/repos/riyapahuja1994/wakeme/downloads",
//     "issues_url": "https://api.github.com/repos/riyapahuja1994/wakeme/issues{/number}",
//     "pulls_url": "https://api.github.com/repos/riyapahuja1994/wakeme/pulls{/number}",
//     "milestones_url": "https://api.github.com/repos/riyapahuja1994/wakeme/milestones{/number}",
//     "notifications_url": "https://api.github.com/repos/riyapahuja1994/wakeme/notifications{?since,all,participating}",
//     "labels_url": "https://api.github.com/repos/riyapahuja1994/wakeme/labels{/name}",
//     "releases_url": "https://api.github.com/repos/riyapahuja1994/wakeme/releases{/id}",
//     "deployments_url": "https://api.github.com/repos/riyapahuja1994/wakeme/deployments",
//     "created_at": "2017-11-23T04:42:06Z",
//     "updated_at": "2017-11-23T04:42:06Z",
//     "pushed_at": "2017-11-23T04:42:07Z",
//     "git_url": "git://github.com/riyapahuja1994/wakeme.git",
//     "ssh_url": "git@github.com:riyapahuja1994/wakeme.git",
//     "clone_url": "https://github.com/riyapahuja1994/wakeme.git",
//     "svn_url": "https://github.com/riyapahuja1994/wakeme",
//     "homepage": null,
//     "size": 0,
//     "stargazers_count": 0,
//     "watchers_count": 0,
//     "language": null,
//     "has_issues": true,
//     "has_projects": true,
//     "has_downloads": true,
//     "has_wiki": true,
//     "has_pages": false,
//     "forks_count": 0,
//     "mirror_url": null,
//     "archived": false,
//     "open_issues_count": 0,
//     "license": null,
//     "forks": 0,
//     "open_issues": 0,
//     "watchers": 0,
//     "default_branch": "master"
//   }
// ]
